/** ISO 3166-1 alpha-2 options for the geo-block MultiSelect. */
export const ISO_COUNTRY_OPTIONS: Array<{ value: string; label: string }> = [
  { value: "AF", label: "AF — Afghanistan" },
  { value: "AL", label: "AL — Albania" },
  { value: "DZ", label: "DZ — Algeria" },
  { value: "AR", label: "AR — Argentina" },
  { value: "AU", label: "AU — Australia" },
  { value: "AT", label: "AT — Austria" },
  { value: "BD", label: "BD — Bangladesh" },
  { value: "BE", label: "BE — Belgium" },
  { value: "BR", label: "BR — Brazil" },
  { value: "BG", label: "BG — Bulgaria" },
  { value: "CA", label: "CA — Canada" },
  { value: "CL", label: "CL — Chile" },
  { value: "CN", label: "CN — China" },
  { value: "CO", label: "CO — Colombia" },
  { value: "HR", label: "HR — Croatia" },
  { value: "CZ", label: "CZ — Czechia" },
  { value: "DK", label: "DK — Denmark" },
  { value: "EG", label: "EG — Egypt" },
  { value: "EE", label: "EE — Estonia" },
  { value: "FI", label: "FI — Finland" },
  { value: "FR", label: "FR — France" },
  { value: "DE", label: "DE — Germany" },
  { value: "GR", label: "GR — Greece" },
  { value: "HK", label: "HK — Hong Kong" },
  { value: "HU", label: "HU — Hungary" },
  { value: "IN", label: "IN — India" },
  { value: "ID", label: "ID — Indonesia" },
  { value: "IE", label: "IE — Ireland" },
  { value: "IL", label: "IL — Israel" },
  { value: "IT", label: "IT — Italy" },
  { value: "JP", label: "JP — Japan" },
  { value: "KE", label: "KE — Kenya" },
  { value: "KR", label: "KR — South Korea" },
  { value: "LV", label: "LV — Latvia" },
  { value: "LT", label: "LT — Lithuania" },
  { value: "MY", label: "MY — Malaysia" },
  { value: "MX", label: "MX — Mexico" },
  { value: "NL", label: "NL — Netherlands" },
  { value: "NZ", label: "NZ — New Zealand" },
  { value: "NG", label: "NG — Nigeria" },
  { value: "NO", label: "NO — Norway" },
  { value: "PK", label: "PK — Pakistan" },
  { value: "PE", label: "PE — Peru" },
  { value: "PH", label: "PH — Philippines" },
  { value: "PL", label: "PL — Poland" },
  { value: "PT", label: "PT — Portugal" },
  { value: "RO", label: "RO — Romania" },
  { value: "RU", label: "RU — Russia" },
  { value: "SA", label: "SA — Saudi Arabia" },
  { value: "RS", label: "RS — Serbia" },
  { value: "SG", label: "SG — Singapore" },
  { value: "SK", label: "SK — Slovakia" },
  { value: "SI", label: "SI — Slovenia" },
  { value: "ZA", label: "ZA — South Africa" },
  { value: "ES", label: "ES — Spain" },
  { value: "SE", label: "SE — Sweden" },
  { value: "CH", label: "CH — Switzerland" },
  { value: "TW", label: "TW — Taiwan" },
  { value: "TH", label: "TH — Thailand" },
  { value: "TR", label: "TR — Türkiye" },
  { value: "UA", label: "UA — Ukraine" },
  { value: "AE", label: "AE — United Arab Emirates" },
  { value: "GB", label: "GB — United Kingdom" },
  { value: "US", label: "US — United States" },
  { value: "VN", label: "VN — Vietnam" },
];
