#!/usr/bin/env node
/**
 * Local bootstrap for TideGuard contributors / operators.
 * Prepares Wrangler types + .dev.vars, then hands off to the /admin wizard.
 *
 * Usage:
 *   npm run setup
 *   npm run setup -- --yes          # non-interactive (no prompts, no long-running dev)
 *   npm run setup -- --yes --dev    # non-interactive, then start wrangler dev
 */
import { randomBytes } from "node:crypto";
import { spawn } from "node:child_process";
import { copyFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { createInterface } from "node:readline";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DEV_VARS = join(ROOT, ".dev.vars");
const DEV_VARS_EXAMPLE = join(ROOT, ".dev.vars.example");
const PLACEHOLDER = "replace-me-with-openssl-rand-hex-32";
const MIN_NODE = 20;

const args = new Set(process.argv.slice(2));
const yes = args.has("--yes") || args.has("-y");
const wantDev = args.has("--dev");

function log(msg = "") {
  console.log(msg);
}

function fail(msg) {
  console.error(`\nError: ${msg}`);
  process.exit(1);
}

function parseDevVars(text) {
  /** @type {Record<string, string>} */
  const out = {};
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    out[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
  }
  return out;
}

function writeTokenSecret(secret) {
  const header = [
    "# Local TideGuard secrets (gitignored).",
    "# Generated by `npm run setup`. Do not commit this file.",
    "",
  ].join("\n");
  writeFileSync(DEV_VARS, `${header}TOKEN_SECRET=${secret}\n`, "utf8");
}

async function prompt(question, defaultYes = true) {
  if (yes) return defaultYes;
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const hint = defaultYes ? "Y/n" : "y/N";
  const answer = await new Promise((resolve) => {
    rl.question(`${question} [${hint}] `, resolve);
  });
  rl.close();
  const normalized = answer.trim().toLowerCase();
  if (!normalized) return defaultYes;
  return normalized === "y" || normalized === "yes";
}

function run(command, commandArgs, { inherit = true } = {}) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, commandArgs, {
      cwd: ROOT,
      stdio: inherit ? "inherit" : "pipe",
      shell: process.platform === "win32",
      env: process.env,
    });
    child.on("error", reject);
    child.on("close", (code) => {
      if (code === 0) resolve();
      else reject(new Error(`${command} ${commandArgs.join(" ")} exited with code ${code}`));
    });
  });
}

async function main() {
  log("TideGuard local setup");
  log("─────────────────────");
  log(
    "This prepares Wrangler types and local secrets. Cloudflare verify and Turnstile finish in the browser at /admin.\n",
  );

  const major = Number(process.versions.node.split(".")[0]);
  if (!Number.isFinite(major) || major < MIN_NODE) {
    fail(`Node.js ${MIN_NODE}+ is required (found ${process.versions.node}).`);
  }
  log(`✓ Node ${process.versions.node}`);

  log("\n→ Regenerating Worker Env types (`wrangler types`)…");
  log("  (Safe to re-run anytime; this is what `npm run types` does.)\n");
  try {
    await run("npx", ["wrangler", "types"]);
  } catch (err) {
    fail(err instanceof Error ? err.message : String(err));
  }
  log("\n✓ worker-configuration.d.ts updated");

  if (!existsSync(DEV_VARS_EXAMPLE)) {
    fail("Missing .dev.vars.example — are you in the TideGuard repo root?");
  }

  if (!existsSync(DEV_VARS)) {
    copyFileSync(DEV_VARS_EXAMPLE, DEV_VARS);
    log("\n→ Created .dev.vars from .dev.vars.example");
  } else {
    log("\n→ Found existing .dev.vars");
  }

  const current = parseDevVars(readFileSync(DEV_VARS, "utf8"));
  const existing = current.TOKEN_SECRET ?? "";
  if (!existing || existing === PLACEHOLDER) {
    const secret = randomBytes(32).toString("hex");
    writeTokenSecret(secret);
    log("✓ Generated a new TOKEN_SECRET and wrote it to .dev.vars");
    log("\n  Copy this for the admin Claim step (shown once):\n");
    log(`  ${secret}\n`);
  } else {
    log("✓ TOKEN_SECRET already set (left unchanged)");
  }

  log("Next steps");
  log("──────────");
  log("1. Start the Worker:  npm run dev");
  log("2. Open:              http://localhost:8787/admin");
  log("3. Claim with your TOKEN_SECRET (from .dev.vars), create username + password");
  log("4. Wizard: Cloudflare verify → Turnstile → Queue → Branding → Finish");
  log("5. Try:               http://localhost:8787/wait  and  /demo");
  log("");
  log("Docs: docs/getting-started.md · docs/admin.md");
  log("");

  const startDev = wantDev || (!yes && (await prompt("Start npm run dev now?", true)));
  if (!startDev) {
    log("Skipped starting the dev server. When ready: npm run dev");
    return;
  }

  log("\n→ Starting wrangler dev (Ctrl+C to stop)…\n");
  await run("npx", ["wrangler", "dev"]);
}

main().catch((err) => {
  fail(err instanceof Error ? err.message : String(err));
});
